### PR TITLE
Add Namada-SelfHost

### PR DESCRIPTION
**Pull request by 0x4r45h**

### CODE REVIEW

**Review by crackerli — COMMENTED** [review]
Thanks for your PR, is your production only work as local node for now and future? Any plan to connect to testnet such as Campfire?
If the answer was for local node only, I think we should modify the label to "Namada devnet self-host".
And, can you make your description more concise(Also pay attention to those capital letters)?

BRs

**Comment by 0x4r45h** [comment]
Its purpose is to launch your own blockchain, so I don't have any plans to connect it to the testnet/mainnet. Perhaps in the future, I might explore adding a fork option similar to what Hardhat does.

Regarding the name, I find "Namada devnet self-host" a bit ambiguous too. How about something like "Namada Local Stack" or "Namada Local Chain"?

**Comment by crackerli** [comment]
I think "Namada Local Chain" is ok.

**Review by crackerli — APPROVED** [review]
Approved, thanks for your PR.

**Pull request merged**
